theme = "gruvbox-dark"
icons = "awesome"


[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
# format = "{icon} {used}/{total}"
format = "{icon} {free}"

[[block]]
block = "memory"
# format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
# format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
format_mem = "{mem_used}"
format_swap = "{swap_used}"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "net"
device = "wlp2s0"
# format = "{ssid} {signal_strength} {ip} {speed_down;K*b} {graph_down;K*b}"
format = "{speed_down;K*B}"
interval = 5

[[block]]
block = "cpu"
interval = 1
# format = "{barchart} {utilization} {frequency}"
format = "{utilization}"

[[block]]
block = "load"
format = "{1m}"
interval = 1

[[block]]
block = "temperature"
# collapsed = false
interval = 10
good = 35
idle = 60
info = 70
warning = 80
# format = "{min} min, {max} max, {average} avg"
format = "{average}C"
# chip = "*-isa-*"
# inputs = ["CPUTIN", "SYSTIN"]

[[block]]
block = "sound"

# [[block]]
# block = "music"
# buttons = ["play", "next"]
# interface_name_exclude = [".*kdeconnect.*", "mpd"]

# [[block]]
# block = "pomodoro"
# length = 25
# break_length = 5

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %T"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
