theme = "gruvbox-dark"
icons = "awesome"


[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}/{MTg}GB"
format_swap = "{SUg}/{STg}GB"

[[block]]
block = "net"
device = "wlp2s0"
# ssid = true
# signal_strength = true
# ip = true
speed_up = false
# graph_up = true
interval = 5
use_bits = false

[[block]]
block = "cpu"
interval = 1

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
on_collapsed_click = "spotify"

# [[block]]
# block = "pomodoro"
# length = 25
# break_length = 5

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %T"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
